### ISSUE TITLE
Plugin can not be applied via plugins block

### ISSUE THREAD

**Issue by britter** [arendd/AspectjGradlePlugin#2]
The plugin can not be applied via the plugins block because it expects the `aspectJVersion` property to be set on the project object. Instead of reading the version from a project property the plugin should rather create it's own project extension and declare a `Property<String>` for the version thereby leveraging lazy configuration APIs.

**Comment by arendd** [comment]
Thanks for the comment, unfortunately I'm not the original developer.
I just created this fork to adapt it to get it working with gradle 5/6, because I was not able to get any other AspectJ Plugin in the gradle plugin repository working.
So therefore, the mention configuration is still original, if you have an important improvement, please feel free to create a pull request, because I’m not an expert for the gradle plugin development and I’m not sure if I would be able to change it accordingly.

**Comment by britter** [comment]
Hey @arendd, great that you took care of this code and also applied some fixes. I'll try to come up with a PR.
